CURRENCY_DICT = {
  "980": "UAN (Ukrainian Hryvnia)",
  "840": "USD (United States Dollar)",
  "978": "EUR (Euro)",
  "036": "AUD (Australian Dollar)",
  "124": "CAD (Canadian Dollar)",
  "156": "CNY (Chinese Yuan)",
  "826": "GBP (British Pound Sterling)",
  "392": "JPY (Japanese Yen)",
  "410": "KRW (South Korean Won)",
  "756": "CHF (Swiss Franc)",
  "643": "RUB (Russian Ruble)",
  "356": "INR (Indian Rupee)",
  "032": "ARL (Argentine Peso)",
  "051": "AMD (Armenian Dram)",
  "050": "XCD (East Caribbean Dollar)",
  "068": "BOB (Bolivian Boliviano)",
  "076": "BRL (Brazilian Real)",
  "124": "CAD (Canadian Dollar)",
  "152": "CLP (Chilean Peso)",
  "170": "COP (Colombian Peso)",
  "188": "CRC (Costa Rican Colón)",
  "191": "HRK (Croatian Kuna)",
  "203": "CZK (Czech Koruna)",
  "208": "DKK (Danish Krone)",
  "214": "DOP (Dominican Peso)",
  "218": "EGP (Egyptian Pound)",
  "222": "SVC (Salvadoran Colón)",
  "230": "ETB (Ethiopian Birr)",
  "232": "EUR (Euro)",
  "238": "FKP (Falkland Islands Pound)",
  "242": "FJD (Fijian Dollar)",
  "270": "GMD (Gambian Dalasi)",
  "344": "HKD (Hong Kong Dollar)",
  "348": "HUF (Hungarian Forint)",
  "352": "ISK (Icelandic Króna)",
  "356": "INR (Indian Rupee)",
  "360": "IDR (Indonesian Rupiah)",
  "364": "IRR (Iranian Rial)",
  "368": "IQD (Iraqi Dinar)",
  "376": "ILS (Israeli New Shekel)",
  "388": "JMD (Jamaican Dollar)",
  "392": "JPY (Japanese Yen)",
  "398": "KZT (Kazakhstani Tenge)",
  "400": "JOD (Jordanian Dinar)",
  "404": "KES (Kenyan Shilling)",
  "408": "KPW (North Korean Won)",
  "414": "KWD (Kuwaiti Dinar)",
  "417": "KGS (Kyrgyzstani Som)",
  "418": "LAK (Lao Kip)",
  "422": "LBP (Lebanese Pound)",
  "426": "LSL (Lesotho Loti)",
  "430": "LRD (Liberian Dollar)",
  "434": "LYD (Libyan Dinar)",
  "446": "MOP (Macanese Pataca)",
  "458": "MYR (Malaysian Ringgit)",
  "462": "MVR (Maldivian Rufiyaa)",
  "480": "MUR (Mauritian Rupee)",
  "484": "MXN (Mexican Peso)",
  "496": "MNT (Mongolian Tögrög)",
  "498": "MDL (Moldovan Leu)",
  "504": "MAD (Moroccan Dirham)",
  "512": "OMR (Omani Rial)",
  "516": "NAD (Namibian Dollar)",
  "524": "NPR (Nepalese Rupee)",
  "532": "ANG (Netherlands Antillean Guilder)",
  "533": "AWG (Aruban Florin)",
  "548": "VUV (Vanuatu Vatu)",
  "554": "NZD (New Zealand Dollar)",
  "558": "NIO (Nicaraguan Córdoba)",
  "578": "NOK (Norwegian Krone)",
  "586": "PKR (Pakistani Rupee)",
  "590": "PAB (Panamanian Balboa)",
  "598": "PGK (Papua New Guinean Kina)",
  "600": "PYG (Paraguayan Guarani)",
  "604": "PEN (Peruvian Sol)",
  "608": "PHP (Philippine Peso)",
  "634": "QAR (Qatari Riyal)",
  "643": "RUB (Russian Ruble)",
  "646": "RWF (Rwandan Franc)",
  "654": "SHP (Saint Helena Pound)",
  "682": "SAR (Saudi Riyal)",
  "690": "SCR (Seychellois Rupee)",
  "694": "SLL (Sierra Leonean Leone)",
  "702": "SGD (Singapore Dollar)",
  "704": "VND (Vietnamese Đồng)",
  "706": "SOS (Somali Shilling)",
  "710": "ZAR (South African Rand)",
  "728": "SSP (South Sudanese Pound)",
  "748": "SZL (Swazi Lilangeni)",
  "752": "SEK (Swedish Krona)",
  "756": "CHF (Swiss Franc)",
  "760": "SYP (Syrian Pound)",
  "764": "THB (Thai Baht)",
  "776": "TOP (Tongan Paʻanga)",
  "780": "TTD (Trinidad and Tobago Dollar)",
  "784": "AED (United Arab Emirates Dirham)",
  "788": "TND (Tunisian Dinar)",
  "800": "UGX (Ugandan Shilling)",
  "807": "MKD (Macedonian Denar)",
  "818": "EGP (Egyptian Pound)",
  "826": "GBP (British Pound Sterling)",
  "834": "TZS (Tanzanian Shilling)",
  "840": "USD (United States Dollar)",
  "858": "UYU (Uruguayan Peso)",
  "860": "UZS (Uzbekistan Som)",
  "882": "WST (Samoan Tālā)",
  "886": "YER (Yemeni Rial)",
  "901": "TWD (New Taiwan Dollar)",
  "931": "CDF (Congolese Franc)",
  "932": "UZS (Uzbekistan Som)",
  "933": "VEF (Venezuelan Bolívar)",
  "934": "VES (Venezuelan Bolívar Soberano)",
  "936": "XAF (Central African CFA Franc)",
  "938": "XCD (East Caribbean Dollar)",
  "941": "XOF (West African CFA Franc)",
  "943": "XPF (CFP Franc)",
  "944": "XOF (West African CFA Franc)",
  "946": "XPF (CFP Franc)",
  "947": "XPF (CFP Franc)",
  "948": "XPF (CFP Franc)",
  "949": "TRY (Turkish Lira)",
  "950": "XPF (CFP Franc)",
  "951": "XPF (CFP Franc)",
  "952": "XPF (CFP Franc)",
  "953": "XPF (CFP Franc)",
  "960": "XDR (Special Drawing Rights)",
  "967": "ZMW (Zambian Kwacha)",
  "968": "ZWL (Zimbabwean Dollar)",
}
