# Generated by Django 4.2.1 on 2023-05-23 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='token_monobank',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id_monobank', models.AutoField(primary_key=True, serialize=False)),
                ('currencyCode', models.CharField(max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creditLimit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_cards', models.CharField(max_length=50)),
                ('iban', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
