# Generated by Django 4.2.1 on 2023-05-27 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_alter_card_type_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20)),
                ('time', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('mcc', models.IntegerField()),
                ('originalMcc', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operationAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currencyCode', models.IntegerField()),
                ('commissionRate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cashbackAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hold', models.BooleanField()),
                ('receiptId', models.CharField(max_length=20)),
                ('counterEdrpou', models.CharField(max_length=20)),
                ('counterIban', models.CharField(max_length=30)),
                ('counterName', models.CharField(max_length=100)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='user_api.card')),
            ],
        ),
    ]
