# Generated by Django 4.2.1 on 2023-05-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='id_monobank',
            new_name='id',
        ),
        migrations.AddField(
            model_name='card',
            name='monobank_id',
            field=models.CharField(max_length=124, null=True),
        ),
    ]
