# Generated by Django 4.2.1 on 2023-05-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_rename_id_monobank_card_id_card_monobank_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiptId',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
