# Generated by Django 4.2.1 on 2023-05-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0007_alter_transaction_counteredrpou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='monobank_id',
            field=models.CharField(max_length=124, null=True, unique=True),
        ),
    ]
