# Generated by Django 4.2.1 on 2023-05-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0008_alter_card_monobank_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cashbackAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='commissionRate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='counterIban',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='counterName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currencyCode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='hold',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mcc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operationAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='originalMcc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
