# Generated by Django 4.2.1 on 2023-06-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0009_alter_transaction_amount_alter_transaction_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
