# Generated by Django 4.2.1 on 2023-06-11 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monobank_id', models.CharField(max_length=124, null=True, unique=True)),
                ('currencyCode', models.CharField(max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creditLimit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_cards', models.IntegerField(choices=[(0, 'fop'), (1, 'white'), (2, 'black'), (3, 'eAid')])),
                ('iban', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
